name: "build-test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
      - run: |
          yarn build && yarn package
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./dist/index.js
        with:
          path: "./examples/website/dist"
          private-key: ${{ secrets.PK }}
          bundlr-endpoint: "http://devnet.bundlr.network"
