name: "build"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn --cwd ./examples/website/
      - run: |
          yarn --cwd ./examples/website/ build
      - uses: ./
        with:
          path: "./examples/website/dist"
          private-key: ${{ secrets.PK }}
          bundlr-endpoint: "http://devnet.bundlr.network"
